### ISSUE TITLE
Brazilian download

### ISSUE THREAD

**Issue by Ryan-Riggs** [Ryan-Riggs/RivRetrieve#15]
@simonmoulds I found a small issue in the brazil discharge download. The last 2 digits in the output dataframe should come after a decimal point. I'm happy to work on this but I didn't want to mess up your workflow while you are working on returning the original data.

**Comment by simonmoulds** [comment]
@Ryan-Riggs - do you mean we need to divide by 100? I see that the returned data are integers, so that would make sense.

**Comment by Ryan-Riggs** [comment]
@simonmoulds Well that's what I thought at first but I think the issue is that some of the raw values contain decimal points and others do not. The code seems to be ignoring the decimal point and so a raw value of 147936.141 is showing up as 147936141. If there are no digits after a decimal point then the code is working fine. 

I removed the unit conversion. Any quick ideas on how to resolve the issue? I'm working on writing some scripts for discharge QA/QC and then I'll work on writing stage functions.

**Comment by simonmoulds** [comment]
@Ryan-Riggs Ah OK - perhaps the character -> numeric conversion is doing something strange. I'll have a look.

**Comment by simonmoulds** [comment]
@Ryan-Riggs I think I've solved the problem. When the `read_delim(...)` function was interpreting commas as formatting rather than a decimal place, such that e.g. "124,000" in the original data would be automatically converted to "124000" in R. Passing `locale=locale(decimal_mark=",")` to `read_delim(...)` solved the problem. 

From some cross checks with published Brazilian data it seems the raw discharge data is in m3/s but the stage data is in centimeters, so I've converted this to meters.

**Comment by Ryan-Riggs** [comment]
@simonmoulds Yeah I think this works, thank you! For some reason the requiring of the `locale` function from `readr` is giving issues. I tried to change it to just import the entire `readr` package but when I run the vignette, I keep getting the error: could not find function "locale". I can keep working on this issue but just wanted to mention it

**Comment by simonmoulds** [comment]
You might need to rebuild the package documentation - I added `@importFrom readr read_delim locale` to `RivRetrieve-package.R`, so all you should need to do is run `devtools::document()` to update the `NAMESPACE` file.

**Comment by Ryan-Riggs** [comment]
Thank you! That solved the problem.
